import Link from 'next/link';

export default async function TermsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const isZh = locale === 'zh';

  return (
    <div className="min-h-screen bg-warm-gradient py-16 px-6">
      <div className="max-w-2xl mx-auto">
        <Link
          href={`/${locale}`}
          className="text-sm text-text-secondary hover:text-brand transition-colors mb-8 inline-block"
        >
          ← {isZh ? '返回首页' : 'Back to Home'}
        </Link>

        <h1 className="text-3xl font-bold text-text-primary mb-2">
          {isZh ? '服务条款' : 'Terms of Service'}
        </h1>
        <p className="text-sm text-text-secondary mb-10">
          {isZh ? '最后更新：2026年3月21日' : 'Last updated: March 21, 2026'}
        </p>

        <div className="prose prose-sm max-w-none space-y-8 text-text-primary">

          <section>
            <h2 className="text-lg font-semibold mb-3">
              {isZh ? '1. 服务说明' : '1. Service Description'}
            </h2>
            <p className="text-text-secondary leading-relaxed">
              {isZh
                ? 'Gallup Strengths Action Plan（gallup-tool.com）是一个基于 AI 的工具，帮助用户将盖洛普 CliftonStrengths 优势转化为可执行的决策建议。本服务与 Gallup 公司没有官方关联或认可。'
                : 'Gallup Strengths Action Plan (gallup-tool.com) is an AI-powered tool that helps users translate their Gallup CliftonStrengths into actionable decision tips. This service is not officially affiliated with or endorsed by Gallup, Inc.'}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              {isZh ? '2. 付款与退款' : '2. Payment & Refunds'}
            </h2>
            <p className="text-text-secondary leading-relaxed">
              {isZh
                ? '完整报告需要一次性付款 $5.99 美元，无订阅费用。由于数字内容的性质，完成付款并生成报告后，我们一般不提供退款。如有异议，请在 7 天内联系我们。'
                : 'Full report access requires a one-time payment of $5.99 USD with no subscription. Due to the nature of digital content, we generally do not offer refunds once payment is completed and the report is generated. For disputes, please contact us within 7 days.'}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              {isZh ? '3. 免责声明' : '3. Disclaimer'}
            </h2>
            <p className="text-text-secondary leading-relaxed">
              {isZh
                ? '本工具生成的内容基于 AI 分析，仅供参考，不构成专业心理咨询、职业建议或任何形式的专业指导。用户应自行判断并承担使用本服务的风险。'
                : 'Content generated by this tool is based on AI analysis and is for reference only. It does not constitute professional psychological counseling, career advice, or any form of professional guidance. Users should exercise their own judgment and bear the risks of using this service.'}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              {isZh ? '4. 知识产权' : '4. Intellectual Property'}
            </h2>
            <p className="text-text-secondary leading-relaxed">
              {isZh
                ? '本网站的设计、代码和内容归 gallup-tool.com 所有。CliftonStrengths 是 Gallup, Inc. 的注册商标。'
                : 'The design, code, and content of this website are owned by gallup-tool.com. CliftonStrengths is a registered trademark of Gallup, Inc.'}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">
              {isZh ? '5. 联系我们' : '5. Contact Us'}
            </h2>
            <p className="text-text-secondary leading-relaxed">
              {isZh ? '如有任何问题，请发送邮件至：' : 'For any questions, please email us at:'}{' '}
              <a href="mailto:hello@gallup-tool.com" className="text-brand hover:underline">
                hello@gallup-tool.com
              </a>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
